### ISSUE TITLE
5 September Status

### ISSUE THREAD

**Issue by aaronjorbin** [aaronjorbin/releasing-a-version-of-wordpress-in-8-hours-or-less#12]
- [x] Update tiktok slide appearance (#18)
- [x] Intro - Maybe something like https://x.com/FrancescaMarano/status/1722236729569210856
- [x] What do you do when your documentation and planning fails? @aaronjorbin #15 
- [x] Remove Steppers from What's Broke (#16)
- [x] Update What's Broke Speaker notes (#16)
- [x] What is the criteria that needs to be met and what factors are considered? @desrosj 
- [x] Who runs a release? @desrosj 
- [x] Decision making in WordPress Core @aaronjorbin 
- [x] Leadership without Authority ( Matt wasn't involved, We drove to a consensus and proceeded) @aaronjorbin 
- [x] Add additional Lessons (What can we learn) @desrosj will expand it
- [x] Move How Updates Work and How Websites work to the front (#13)
